export const chapters = [
  {
    id: "general",
    titleKey: "privacy.chapters.general.title",
    content: [
      { textKey: "privacy.chapters.general.1_1", type: "p" },
      { textKey: "privacy.chapters.general.1_2", type: "p" },
      { textKey: "privacy.chapters.general.1_3", type: "p" },
      { textKey: "privacy.chapters.general.1_4", type: "p" },
      { textKey: "privacy.chapters.general.li1", type: "li" },
      { textKey: "privacy.chapters.general.li2", type: "li" },
      { textKey: "privacy.chapters.general.li3", type: "li" },
      { textKey: "privacy.chapters.general.li4", type: "li" },
    ],
  },
  {
    id: "data-composition",
    titleKey: "privacy.chapters.dataComposition.title",
    content: [
      { textKey: "privacy.chapters.dataComposition.2_1", type: "p" },
      { textKey: "privacy.chapters.dataComposition.li1", type: "li" },
      { textKey: "privacy.chapters.dataComposition.li2", type: "li" },
      { textKey: "privacy.chapters.dataComposition.li3", type: "li" },
      { textKey: "privacy.chapters.dataComposition.li4", type: "li" },
      { textKey: "privacy.chapters.dataComposition.2_2", type: "p" },
    ],
  },
  {
    id: "processing-purposes",
    titleKey: "privacy.chapters.processingPurposes.title",
    content: [
      { textKey: "privacy.chapters.processingPurposes.3_1", type: "p" },
      { textKey: "privacy.chapters.processingPurposes.li1", type: "li" },
      { textKey: "privacy.chapters.processingPurposes.li2", type: "li" },
      { textKey: "privacy.chapters.processingPurposes.li3", type: "li" },
      { textKey: "privacy.chapters.processingPurposes.li4", type: "li" },
      { textKey: "privacy.chapters.processingPurposes.li5", type: "li" },
      { textKey: "privacy.chapters.processingPurposes.li6", type: "li" },
      { textKey: "privacy.chapters.processingPurposes.li7", type: "li" },
    ],
  },
  {
    id: "legal-basis",
    titleKey: "privacy.chapters.legalBasis.title",
    content: [
      { textKey: "privacy.chapters.legalBasis.4_1", type: "p" },
      { textKey: "privacy.chapters.legalBasis.li1", type: "li" },
      { textKey: "privacy.chapters.legalBasis.li2", type: "li" },
      { textKey: "privacy.chapters.legalBasis.li3", type: "li" },
    ],
  },
  {
    id: "processing-procedure",
    titleKey: "privacy.chapters.processingProcedure.title",
    content: [
      { textKey: "privacy.chapters.processingProcedure.5_1", type: "p" },
      { textKey: "privacy.chapters.processingProcedure.5_2", type: "p" },
      { textKey: "privacy.chapters.processingProcedure.5_3", type: "p" },
      { textKey: "privacy.chapters.processingProcedure.li1", type: "li" },
      { textKey: "privacy.chapters.processingProcedure.li2", type: "li" },
      { textKey: "privacy.chapters.processingProcedure.li3", type: "li" },
      { textKey: "privacy.chapters.processingProcedure.li4", type: "li" },
      { textKey: "privacy.chapters.processingProcedure.5_4", type: "p" },
      { textKey: "privacy.chapters.processingProcedure.5_5", type: "p" },
    ],
  },
  {
    id: "user-rights",
    titleKey: "privacy.chapters.userRights.title",
    content: [
      { textKey: "privacy.chapters.userRights.6_1", type: "p" },
      { textKey: "privacy.chapters.userRights.li1", type: "li" },
      { textKey: "privacy.chapters.userRights.li2", type: "li" },
      { textKey: "privacy.chapters.userRights.li3", type: "li" },
      { textKey: "privacy.chapters.userRights.li4", type: "li" },
      { textKey: "privacy.chapters.userRights.li5", type: "li" },
      { textKey: "privacy.chapters.userRights.li6", type: "li" },
    ],
  },
  {
    id: "data-protection",
    titleKey: "privacy.chapters.dataProtection.title",
    content: [
      { textKey: "privacy.chapters.dataProtection.7_1", type: "p" },
      { textKey: "privacy.chapters.dataProtection.7_2", type: "p" },
      { textKey: "privacy.chapters.dataProtection.li1", type: "li" },
      { textKey: "privacy.chapters.dataProtection.li2", type: "li" },
      { textKey: "privacy.chapters.dataProtection.li3", type: "li" },
      { textKey: "privacy.chapters.dataProtection.li4", type: "li" },
      { textKey: "privacy.chapters.dataProtection.li5", type: "li" },
    ],
  },
  {
    id: "final-provisions",
    titleKey: "privacy.chapters.finalProvisions.title",
    content: [
      { textKey: "privacy.chapters.finalProvisions.8_1", type: "p" },
      { textKey: "privacy.chapters.finalProvisions.8_2", type: "p" },
      { textKey: "privacy.chapters.finalProvisions.8_3", type: "p" },
    ],
  },
];
