const requests = [
  {
    id: 1,
    title: "Заявка на ремонт ванной комнаты",
    status: "В обработке",
    date: "2026-01-01",
    district: "Центральный",
    street: "Независимости",
    house: "10",
    entrance: "2",
    floor: "5",
    apartment: "45",
    description:
      "Протечка трубы под раковиной. Необходима замена смесителя и устранение течи.",
    photo: null,
    location: { lat: 53.9, lng: 27.5667 },
    priority: "Высокий",
    type: "Сантехника",
    comments: [
      {
        text: "Сантехник назначен на завтра, 10:00",
        author: "Иванов И.И.",
        time: "2026-01-01 14:30",
      },
      {
        text: "Закуплены необходимые материалы",
        author: "Петров П.П.",
        time: "2026-01-01 16:45",
      },
    ],
  },
  {
    id: 2,
    title: "Уборка квартиры после ремонта",
    status: "Выполнено",
    date: "2026-01-01",
    district: "Советский",
    street: "Купалы",
    house: "15",
    entrance: "1",
    floor: "3",
    apartment: "12",
    description:
      "Комплексная уборка 3-комнатной квартиры после капитального ремонта.",
    photo: "photo_cleaning.jpg",
    location: { lat: 53.91, lng: 27.55 },
    priority: "Средний",
    type: "Уборка",
    comments: [
      {
        text: "Уборка выполнена успешно, клиент доволен",
        author: "Петров П.П.",
        time: "2026-01-01 16:45",
      },
    ],
  },
  {
    id: 3,
    title: "Доставка мебели в квартиру",
    status: "Отклонено",
    date: "2026-01-01",
    district: "Партизанский",
    street: "Московская",
    house: "20",
    entrance: "3",
    floor: "7",
    apartment: "70",
    description: "Требуется доставка дивана и шкафа на 7 этаж.",
    photo: null,
    location: { lat: 53.92, lng: 27.57 },
    priority: "Средний",
    type: "Доставка",
    comments: [
      {
        text: "Доставка перенесена на следующую неделю",
        author: "Сидоров С.С.",
        time: "2026-01-01 11:20",
      },
    ],
  },
  {
    id: 4,
    title: "Ремонт электропроводки",
    status: "В обработке",
    date: "2026-01-01",
    district: "Фрунзенский",
    street: "Пушкина",
    house: "5",
    entrance: "4",
    floor: "9",
    apartment: "90",
    description: "Замена старой алюминиевой проводки на медную.",
    photo: null,
    location: { lat: 53.93, lng: 27.58 },
    priority: "Высокий",
    type: "Электрика",
    comments: [
      {
        text: "Электрик выедет 12 декабря",
        author: "Николаев Д.Д.",
        time: "2026-01-01 10:00",
      },
    ],
  },
  {
    id: 5,
    title: "Устранение засора канализации",
    status: "Выполнено",
    date: "2026-01-02",
    district: "Ленинский",
    street: "Горького",
    house: "25",
    entrance: "2",
    floor: "4",
    apartment: "38",
    description: "Сильный засор в стояке на 4 этаже.",
    photo: "photo_clog.jpg",
    location: { lat: 53.89, lng: 27.56 },
    priority: "Критический",
    type: "Сантехника",
    comments: [
      {
        text: "Экстренный вызов. Выезд в течение часа",
        author: "Васильев М.М.",
        time: "2026-01-02 08:30",
      },
    ],
  },
  {
    id: 6,
    title: "Установка межкомнатных дверей",
    status: "В обработке",
    date: "2026-01-02",
    district: "Октябрьский",
    street: "Космонавтов",
    house: "12",
    entrance: "3",
    floor: "2",
    apartment: "21",
    description: "Установка 4 межкомнатных дверей.",
    photo: null,
    location: { lat: 53.88, lng: 27.54 },
    priority: "Низкий",
    type: "Ремонт",
    comments: [
      {
        text: "Ожидается поставка фурнитуры",
        author: "Кузнецов А.А.",
        time: "2026-01-02 11:00",
      },
    ],
  },
  {
    id: 7,
    title: "Покраска подъезда",
    status: "Выполнено",
    date: "2026-01-02",
    district: "Советский",
    street: "Янки Купалы",
    house: "8",
    entrance: "1",
    floor: "0",
    apartment: "0",
    description: "Капитальная покраска стен и перил в подъезде.",
    photo: "photo_painting.jpg",
    location: { lat: 53.92, lng: 27.55 },
    priority: "Средний",
    type: "Благоустройство",
    comments: [
      {
        text: "Работы начаты",
        author: "Попов С.С.",
        time: "2026-01-02 09:00",
      },
    ],
  },
  {
    id: 8,
    title: "Замена лифта",
    status: "В обработке",
    date: "2026-01-03",
    district: "Первомайский",
    street: "Калинина",
    house: "30",
    entrance: "2",
    floor: "0",
    apartment: "0",
    description: "Плановый ремонт лифта.",
    photo: null,
    location: { lat: 53.94, lng: 27.59 },
    priority: "Высокий",
    type: "Лифтовое хозяйство",
    comments: [
      {
        text: "Ожидаем поставку запчастей",
        author: "Морозов В.В.",
        time: "2026-01-03 14:20",
      },
    ],
  },
  {
    id: 9,
    title: "Уборка снега во дворе",
    status: "Выполнено",
    date: "2026-01-03",
    district: "Заводской",
    street: "Советская",
    house: "42",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Расчистка дворовой территории от снега.",
    photo: "photo_snow.jpg",
    location: { lat: 53.85, lng: 27.53 },
    priority: "Средний",
    type: "Благоустройство",
    comments: [
      {
        text: "Работы выполнены",
        author: "Зайцев И.И.",
        time: "2026-01-03 16:45",
      },
    ],
  },
  {
    id: 10,
    title: "Ремонт крыши",
    status: "Отклонено",
    date: "2026-01-03",
    district: "Московский",
    street: "Минская",
    house: "18",
    entrance: "0",
    floor: "9",
    apartment: "0",
    description: "Протечка крыши в районе 9 этажа.",
    photo: null,
    location: { lat: 53.9, lng: 27.6 },
    priority: "Высокий",
    type: "Кровельные работы",
    comments: [
      {
        text: "Работы перенесены на весну",
        author: "Соколов П.П.",
        time: "2026-01-03 13:10",
      },
    ],
  },
  {
    id: 11,
    title: "Установка домофона",
    status: "В обработке",
    date: "2026-01-04",
    district: "Фрунзенский",
    street: "Октябрьская",
    house: "7",
    entrance: "1",
    floor: "0",
    apartment: "0",
    description: "Монтаж новой системы домофона.",
    photo: null,
    location: { lat: 53.91, lng: 27.57 },
    priority: "Средний",
    type: "Системы безопасности",
    comments: [
      {
        text: "Ожидается согласование с жильцами",
        author: "Павлов К.К.",
        time: "2026-01-04 10:45",
      },
    ],
  },
  {
    id: 12,
    title: "Вывоз мусора",
    status: "Выполнено",
    date: "2026-01-04",
    district: "Центральный",
    street: "Ленина",
    house: "33",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Вывоз строительного мусора.",
    photo: "photo_garbage.jpg",
    location: { lat: 53.89, lng: 27.57 },
    priority: "Низкий",
    type: "Вывоз мусора",
    comments: [
      {
        text: "Вывезено 2 контейнера мусора",
        author: "Белов Д.Д.",
        time: "2026-01-04 14:20",
      },
    ],
  },
  {
    id: 13,
    title: "Ремонт детской площадки",
    status: "В обработке",
    date: "2026-01-04",
    district: "Советский",
    street: "Чкалова",
    house: "22",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Замена сломанных элементов на детской площадке.",
    photo: null,
    location: { lat: 53.93, lng: 27.56 },
    priority: "Средний",
    type: "Благоустройство",
    comments: [
      {
        text: "Заказаны новые качели",
        author: "Тихонов Н.Н.",
        time: "2026-01-04 11:30",
      },
    ],
  },
  {
    id: 14,
    title: "Замена окон",
    status: "Выполнено",
    date: "2026-01-05",
    district: "Партизанский",
    street: "Героев",
    house: "14",
    entrance: "2",
    floor: "6",
    apartment: "62",
    description: "Установка пластиковых окон.",
    photo: "photo_windows.jpg",
    location: { lat: 53.87, lng: 27.58 },
    priority: "Средний",
    type: "Ремонт",
    comments: [
      {
        text: "Окна установлены",
        author: "Комаров А.А.",
        time: "2026-01-05 17:00",
      },
    ],
  },
  {
    id: 15,
    title: "Устранение течи в подвале",
    status: "В обработке",
    date: "2026-01-05",
    district: "Ленинский",
    street: "Красноармейская",
    house: "9",
    entrance: "0",
    floor: "-1",
    apartment: "0",
    description: "Обнаружена течь в системе отопления.",
    photo: null,
    location: { lat: 53.86, lng: 27.55 },
    priority: "Критический",
    type: "Сантехника",
    comments: [
      {
        text: "Экстренный вызов",
        author: "Громов С.С.",
        time: "2026-01-05 07:45",
      },
    ],
  },
  {
    id: 16,
    title: "Проверка пожарной безопасности",
    status: "Выполнено",
    date: "2026-01-05",
    district: "Октябрьский",
    street: "Победы",
    house: "28",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Плановая проверка пожарных гидрантов.",
    photo: "photo_fire.jpg",
    location: { lat: 53.95, lng: 27.56 },
    priority: "Высокий",
    type: "Проверка",
    comments: [
      {
        text: "Проверка завершена",
        author: "Филиппов В.В.",
        time: "2026-01-05 15:20",
      },
    ],
  },
  {
    id: 17,
    title: "Установка кондиционера",
    status: "Отклонено",
    date: "2026-01-06",
    district: "Московский",
    street: "Горная",
    house: "3",
    entrance: "1",
    floor: "8",
    apartment: "81",
    description: "Монтаж сплит-системы.",
    photo: null,
    location: { lat: 53.92, lng: 27.61 },
    priority: "Низкий",
    type: "Монтаж",
    comments: [
      {
        text: "Клиент отказался от услуги",
        author: "Данилов М.М.",
        time: "2026-01-06 12:15",
      },
    ],
  },
  {
    id: 18,
    title: "Обрезка деревьев",
    status: "В обработке",
    date: "2026-01-06",
    district: "Заводской",
    street: "Рабочая",
    house: "11",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Санитарная обрезка сухих ветвей.",
    photo: null,
    location: { lat: 53.84, lng: 27.52 },
    priority: "Средний",
    type: "Благоустройство",
    comments: [
      {
        text: "Ожидается получение разрешения",
        author: "Соловьев А.А.",
        time: "2026-01-06 09:00",
      },
    ],
  },
  {
    id: 19,
    title: "Ремонт подъездного освещения",
    status: "Выполнено",
    date: "2026-01-07",
    district: "Первомайский",
    street: "Солнечная",
    house: "6",
    entrance: "3",
    floor: "0",
    apartment: "0",
    description: "Замена перегоревших ламп.",
    photo: "photo_lighting.jpg",
    location: { lat: 53.96, lng: 27.58 },
    priority: "Высокий",
    type: "Электрика",
    comments: [
      {
        text: "Установлены энергосберегающие лампы",
        author: "Михайлов П.П.",
        time: "2026-01-07 13:45",
      },
    ],
  },
  {
    id: 20,
    title: "Установка почтовых ящиков",
    status: "В обработке",
    date: "2026-01-07",
    district: "Фрунзенский",
    street: "Школьная",
    house: "19",
    entrance: "1",
    floor: "1",
    apartment: "0",
    description: "Монтаж новых почтовых ящиков.",
    photo: null,
    location: { lat: 53.94, lng: 27.57 },
    priority: "Низкий",
    type: "Монтаж",
    comments: [
      {
        text: "Ящики заказаны",
        author: "Алексеев И.И.",
        time: "2026-01-07 10:20",
      },
    ],
  },
  {
    id: 21,
    title: "Ремонт крыльца",
    status: "В обработке",
    date: "2026-01-07",
    district: "Ленинский",
    street: "Горького",
    house: "25",
    entrance: "2",
    floor: "0",
    apartment: "0",
    description: "Ремонт бетонного крыльца",
    photo: null,
    location: { lat: 53.89, lng: 27.56 },
    priority: "Средний",
    type: "Ремонт",
    comments: [
      {
        text: "Заказаны материалы",
        author: "Семенов С.С.",
        time: "2026-01-07 11:30",
      },
    ],
  },
  {
    id: 22,
    title: "Замена труб отопления",
    status: "Выполнено",
    date: "2026-01-08",
    district: "Центральный",
    street: "Независимости",
    house: "10",
    entrance: "2",
    floor: "0",
    apartment: "0",
    description: "Замена старых труб отопления в подвале",
    photo: null,
    location: { lat: 53.9, lng: 27.5667 },
    priority: "Высокий",
    type: "Сантехника",
    comments: [
      {
        text: "Работы выполнены",
        author: "Васильев М.М.",
        time: "2026-01-08 14:00",
      },
    ],
  },
  {
    id: 23,
    title: "Установка видеонаблюдения",
    status: "В обработке",
    date: "2026-01-08",
    district: "Советский",
    street: "Купалы",
    house: "15",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Монтаж системы видеонаблюдения",
    photo: null,
    location: { lat: 53.91, lng: 27.55 },
    priority: "Высокий",
    type: "Системы безопасности",
    comments: [
      {
        text: "Ожидается оборудование",
        author: "Павлов К.К.",
        time: "2026-01-08 10:00",
      },
    ],
  },
  {
    id: 24,
    title: "Уборка территории",
    status: "Выполнено",
    date: "2026-01-08",
    district: "Партизанский",
    street: "Московская",
    house: "20",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Уборка придомовой территории",
    photo: null,
    location: { lat: 53.92, lng: 27.57 },
    priority: "Низкий",
    type: "Уборка",
    comments: [
      {
        text: "Территория убрана",
        author: "Зайцев И.И.",
        time: "2026-01-08 16:00",
      },
    ],
  },
  {
    id: 25,
    title: "Ремонт забора",
    status: "В обработке",
    date: "2026-01-08",
    district: "Фрунзенский",
    street: "Пушкина",
    house: "5",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Ремонт деревянного забора",
    photo: null,
    location: { lat: 53.93, lng: 27.58 },
    priority: "Средний",
    type: "Ремонт",
    comments: [
      {
        text: "Закуплены доски",
        author: "Попов С.С.",
        time: "2026-01-08 09:30",
      },
    ],
  },
  {
    id: 26,
    title: "Замена счетчиков воды",
    status: "Выполнено",
    date: "2026-01-09",
    district: "Ленинский",
    street: "Горького",
    house: "25",
    entrance: "2",
    floor: "1",
    apartment: "3",
    description: "Поверка и замена счетчиков воды",
    photo: null,
    location: { lat: 53.89, lng: 27.56 },
    priority: "Средний",
    type: "Сантехника",
    comments: [
      {
        text: "Счетчики заменены",
        author: "Васильев М.М.",
        time: "2026-01-09 11:00",
      },
    ],
  },
  {
    id: 27,
    title: "Ремонт кровли",
    status: "В обработке",
    date: "2026-01-09",
    district: "Октябрьский",
    street: "Космонавтов",
    house: "12",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Локальный ремонт кровли",
    photo: null,
    location: { lat: 53.88, lng: 27.54 },
    priority: "Высокий",
    type: "Кровельные работы",
    comments: [
      {
        text: "Ожидаем кровельные материалы",
        author: "Соколов П.П.",
        time: "2026-01-09 13:00",
      },
    ],
  },
  {
    id: 28,
    title: "Установка антивандальных ламп",
    status: "Выполнено",
    date: "2026-01-09",
    district: "Советский",
    street: "Янки Купалы",
    house: "8",
    entrance: "1",
    floor: "0",
    apartment: "0",
    description: "Замена обычных ламп на антивандальные",
    photo: null,
    location: { lat: 53.92, lng: 27.55 },
    priority: "Средний",
    type: "Электрика",
    comments: [
      {
        text: "Лампы установлены",
        author: "Михайлов П.П.",
        time: "2026-01-09 15:30",
      },
    ],
  },
  {
    id: 29,
    title: "Вывоз старой мебели",
    status: "Отклонено",
    date: "2026-01-09",
    district: "Первомайский",
    street: "Калинина",
    house: "30",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Вывоз старой мебели из подвала",
    photo: null,
    location: { lat: 53.94, lng: 27.59 },
    priority: "Низкий",
    type: "Вывоз мусора",
    comments: [
      {
        text: "Отложено до весны",
        author: "Белов Д.Д.",
        time: "2026-01-09 10:15",
      },
    ],
  },
  {
    id: 30,
    title: "Ремонт детской горки",
    status: "В обработке",
    date: "2026-01-09",
    district: "Заводской",
    street: "Советская",
    house: "42",
    entrance: "0",
    floor: "0",
    apartment: "0",
    description: "Ремонт сломанной детской горки",
    photo: null,
    location: { lat: 53.85, lng: 27.53 },
    priority: "Средний",
    type: "Благоустройство",
    comments: [
      {
        text: "Заказаны запчасти",
        author: "Тихонов Н.Н.",
        time: "2026-01-09 14:45",
      },
    ],
  },
];

export default requests;
