export const categoryMap = {
  1: "hotWater",
  2: "electricity",
  3: "services",
  4: "houseSanitation",
  5: "heating",
  6: "landscaping",
  7: "waterSupply",
  8: "construction",
  9: "territorySanitation",
  11: "zpuMaintenance",
  12: "elevatorMaintenance",
  13: "wasteManagement",
  14: "coldWater",
  15: "sewerage",
  16: "roads",
  17: "roofing",
  18: "streetLighting",
  19: "publicPlaces",
  20: "jointRepair",
  21: "buildingMaintenance",
  22: "ads",
};
